"""Initial migration

Revision ID: 0b099ed4a0cd
Revises: 
Create Date: 2021-01-17 16:31:45.369190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b099ed4a0cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_admins_username'), 'admins', ['username'])
    op.drop_constraint('admins_username_key', 'admins', type_='unique')
    op.create_unique_constraint(op.f('uq_anime_info_anime_id'), 'anime_info', ['anime_id'])
    op.create_unique_constraint(op.f('uq_anime_info_title'), 'anime_info', ['title'])
    op.drop_constraint('anime_info_title_key', 'anime_info', type_='unique')
    op.create_unique_constraint(op.f('uq_episodes_episode_id'), 'episodes', ['episode_id'])
    op.create_unique_constraint(op.f('uq_genres_genre_name'), 'genres', ['genre_name'])
    op.drop_constraint('genres_genre_name_key', 'genres', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint('genres_genre_name_key', 'genres', ['genre_name'])
    op.drop_constraint(op.f('uq_genres_genre_name'), 'genres', type_='unique')
    op.drop_constraint(op.f('uq_episodes_episode_id'), 'episodes', type_='unique')
    op.create_unique_constraint('anime_info_title_key', 'anime_info', ['title'])
    op.drop_constraint(op.f('uq_anime_info_title'), 'anime_info', type_='unique')
    op.drop_constraint(op.f('uq_anime_info_anime_id'), 'anime_info', type_='unique')
    op.create_unique_constraint('admins_username_key', 'admins', ['username'])
    op.drop_constraint(op.f('uq_admins_username'), 'admins', type_='unique')
    # ### end Alembic commands ###
