"""Add confirmation table

Revision ID: c6cc50d52a2f
Revises: d75948751bd4
Create Date: 2021-01-19 15:55:26.048269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6cc50d52a2f'
down_revision = 'd75948751bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmations',
    sa.Column('confirmation_id', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], name=op.f('fk_confirmations_user_id_users')),
    sa.PrimaryKeyConstraint('confirmation_id', name=op.f('pk_confirmations'))
    )
    op.drop_column('users', 'activated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('confirmations')
    # ### end Alembic commands ###
